### ISSUE TITLE
Create github actions, utils sub-module

### ISSUE THREAD

**Issue by arita37** [qdrant/qdrant-client#16]
Hello,

A couple of comments.

1)
Through Github actions, 
we can launch a docker with qdrant server and test the client  in/out (ie integration tests)
  can provide it through PR if you have interest.
  
  2)  It would be a useful to create a sub-module:
       qdrant_client.contrib
       
       So, community can PR into it and add utlities (like converion faiss --> Qdrant ).
       
       Can provide the faiss converion util, if you have interest.

**Comment by joein** [comment]
Hello

Sorry that we didn't respond at the time the issue was created

As of now
1. We are using github actions for our tests
2. Imho sub-module is not a best option to implement conversions from other providers

Closing it at the moment, feel free to open an issue/discussion or visit our [Discord](https://discord.com/channels/907569970500743200/928649303898075196) in case of any questions or suggestions
