### ISSUE TITLE
Is there method to close connection?

### ISSUE THREAD

**Issue by bartekga** [qdrant/qdrant-client#193]
Is there a method of terminating the database connection/deleting the database from memory?

**Comment by Fluder-Paradyne** [comment]
I am getting 
`ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.176.7', 33516), raddr=('192.168.176.2', 6333)>
`
is there any method for this

**Comment by joein** [comment]
There is no method to terminate connection in user interface, we close grpc connections during object deletion stage
In other cases, we relied on the underlying cleaners.

We probably can expose method to close http connections explicitly or will add it into the `__del__` as well

@Fluder-Paradyne could you provide more information about your setup please? Including python version, qdrant-client version, os? Code sample to reproduce the issue is appreciated.

**Comment by Fluder-Paradyne** [comment]
It is hard to replicate with a simple script 
I tried writing one but It was not getting this warning

basically there could be multiple client objects at the same time
I know it is not the best way, but in the use case I am working on it is hard to pass around single client.
so far in my testing I am only getting warnings, so I am not too concerned

It would be great if there is a `close` or `__del__`  method so, we can just close the client once work is done 
instead of waiting for gc to take care of this

thanks :smile:

**Comment by michael-newsrx** [comment]
I just ran into this issue in a Jupyter notebook.

Using a local client, if a second copy instantiation is attempted, if fails. There does not appear to be a way to cleanly close the client. I recommend adding a .close() as well as auto close via context manager if possible.

**Comment by joein** [comment]
#227

**Comment by joein** [comment]
@michael-newsrx I will look into the possible options with local mode a bit later

**Comment by joein** [comment]
@michael-newsrx local mode close method will be delivered with #227 as well

**Comment by joein** [comment]
supported as of 1.4.0, feel free to re-open the issue in case of troubles
