### ISSUE TITLE
How to generate grpc client?

### ISSUE THREAD

**Issue by zzzz-vincent** [qdrant/qdrant-client#206]
Hi, I was attempting to add GeoPolygon Filter to the local mode. However, after I added GeoPolygon into proto file, I found the script used to generate python grpc client was not working. It seems that the given script in `generate_grpc_client` is trying to get the proto files from master branch which will overwrite my changes.
Then I was trying to directly use the line `python -m grpc_tools.protoc --proto_path=qdrant_client/proto/ -I ./qdrant_client/grpc ./qdrant_client/proto/*.proto --python_out=./qdrant_client/grpc --grpc_python_out=./qdrant_client/grpc` for generation. However, I found it changed lots of files. And some code lines are missing after the change, eg:
```
ReadConsistency = _reflection.GeneratedProtocolMessageType('ReadConsistency', (_message.Message,), {
  'DESCRIPTOR' : _READCONSISTENCY,
  '__module__' : 'points_pb2'
  # @@protoc_insertion_point(class_scope:qdrant.ReadConsistency)
  })
_sym_db.RegisterMessage(ReadConsistency)

PointId = _reflection.GeneratedProtocolMessageType('PointId', (_message.Message,), {
  'DESCRIPTOR' : _POINTID,
  '__module__' : 'points_pb2'
  # @@protoc_insertion_point(class_scope:qdrant.PointId)
  })
_sym_db.RegisterMessage(PointId)
```
I was wondering what is a correct way to generate the python client?

**Comment by joein** [comment]
Hi @zzzz-vincent 

You don't need to generate grpc client to add a new feature to the local mode, since it does not make any requests and just operates with local structures.

AFAIK, the script in tools is correct, but requires a particular version of `protoc`.
`protoc` started to generate oython clients with `Builder` entity, we need to use previous version.

I think @generall can tell more details

**Comment by zzzz-vincent** [comment]
Thanks, I see what you mean. Yes this makes sense.
