### ISSUE TITLE
Is the python client thread safe?

### ISSUE THREAD

**Issue by mapa17** [qdrant/qdrant-client#246]
Hi, I am considering qdrant for my project and I wanted to double check if the python client is thread safe. I saw in a simple demo https://github.com/qdrant/qdrant_demo/tree/master 

That a initialized client is used in an fastapi endpoint of which (its my understanding) they can be multiple threads running at the same time.

Just to be on the save side. A similar (multi threaded rest-api endpoints) setup is possible for production?

thx,
Manuel

**Comment by generall** [comment]
Hi @mapa17, FastAPI usually operates with processes rather than threads. For example one of the popular ASGI web server `uvicorn` spawns a process for each web worker. In this case you would get 2 copies of QdrantClient, one per worker. This is safe to use QdrantClient in this manner.

Thread-level parallelization is usually not available in high level python due to GIL
