### ISSUE TITLE
create_full_snapshot(wait='true') 

### ISSUE THREAD

**Issue by shatealaboxiaowang** [qdrant/qdrant-client#254]
Dear：

Hello, thank you for your code, but when I run the code create_full_snapshot(wait='true'), an error occurs. The error content is as follows: 
      AssertionError: Unknown arguments: ['wait'], 
what is the reason?

Hope to get your reply

**Comment by grumpyp** [comment]
Wait is a `boolean`, in your case you pass a `string`. The `Exception` is confusing tho.

try `create_full_snapshot(wait=True)`

documentation:
https://qdrant.tech/documentation/concepts/snapshots/?selector=aHRtbCA%2BIGJvZHkgPiBkaXY6bnRoLW9mLXR5cGUoMSkgPiBzZWN0aW9uID4gZGl2ID4gZGl2ID4gZGl2ID4gYXJ0aWNsZSA%2BIGgzOm50aC1vZi10eXBlKDcp#create-snapshot

https://qdrant.github.io/qdrant/redoc/index.html#tag/collections/operation/create_snapshot

**Comment by joein** [comment]
I started fixing the problem, however the issue seems to be deeper that it seemed to be from the first glance.

The problem is that our client generator struggles to generate correct functions for the cases where there are two kind of responses available. 
E.g. in `create_snapshot` there are 2 possible 20x responses: 200 with status=ok and 202 with status=accepted. 
Internally `send` function only supports response 200 at fails to work with 202.
There are 2 problems: firstly, it just does not accept code 202, secondly, it parses a response according to a passed response type, which is `InlineResponse20010` in case of `create_snapshot`. 
To deal with this problem we need either improve our generator or get rid of enums in status field and instead return just a string with additional description in a model's dedicated field.

cc: @generall

**Comment by joein** [comment]
#318

**Comment by joein** [comment]
#370 

https://github.com/qdrant/qdrant/pull/2928

**Comment by joein** [comment]
should be available as of qdrant-client==1.7.0 🎆 

feel free to re-open the issue in case of any problems
