### ISSUE TITLE
upload_records() calls in _migrate_collection() should use wait=True

### ISSUE THREAD

**Issue by andrew-titus** [qdrant/qdrant-client#403]
Since the calls to upload_records ([here](https://github.com/qdrant/qdrant-client/blob/6d019e67a133bea87a96bce388f5b901cdae1287/qdrant_client/migrate/migrate.py#L119) and [here](https://github.com/qdrant/qdrant-client/blob/6d019e67a133bea87a96bce388f5b901cdae1287/qdrant_client/migrate/migrate.py#L124)) in _migrate_collection() do not use `wait=True` (which defaults to `False`), the assertion statement at the end of the function that checks that the vector counts match often fails when migrating content from a local client to a remote client. Since we are checking that they match, we should wait for any uploads to complete for consistency, so this should either be set to `wait=True` directly or at least be exposed as a kwarg for users. Thanks!

**Comment by shivas1516** [comment]
I would like to take on this issue. After reviewing the code, I understand that the calls to `upload_records` in `_migrate_collection()` may not wait for uploads to complete, potentially leading to inconsistencies in vector counts. I plan to address this.
If there are any specific considerations or preferences regarding the solution, please let me know. I'll keep you updated on my progress.

Looking forward to contributing!

**Comment by joein** [comment]
Thanks for highlighting this issue!

I believe the main issue with `upload_records` in the loop had already been resolved by @agourlay 

The remaining part of it with a corner case should be fixed with #428 and available with the next release, thanks @shivas1516 

Feel free to re-open the issue if the problems is reproducible in `qdrant-client 1.7.1` (should be available this week)
