### ISSUE TITLE
query_text param not working for qdrant_client.search

### ISSUE THREAD

**Issue by giacomobartoli** [qdrant/qdrant-client#482]
qdrant_client = 1.7.2

The following snippet of code returns an error:

`qdrant_client.search(collection_name="my_collection", query_text="my_text")`

The error is:

`TypeError: QdrantClient.search() missing 1 required positional argument: 'query_vector'`

According to the [README](https://github.com/qdrant/qdrant-client/) is should be possible to use `query_text` instead of `query_vector`.
fastembed is installed and upgraded.

I went through the source code and I found out that the query_text param does not exists:
https://github.com/qdrant/qdrant-client/blob/master/qdrant_client/qdrant_client.py

Any help for that?

**Comment by joein** [comment]
hi @giacomobartoli 

you are looking for another method - `query`, and it indeed accepts `query_text`

**Comment by geetu040** [comment]
QdrantClient inherits methods from QdrantFastembedMixin so you should use qdrant_client.search method instead

```python
qdrant_client.search(collection_name="my_collection", query_text="my_text")
```

If you go through the source code you should find the method here
https://github.com/qdrant/qdrant-client/blob/master/qdrant_client/qdrant_fastembed.py#L325

**Comment by joein** [comment]
@geetu040 unfortunately, your answer is confusing, could you correct it please?

**Comment by giacomobartoli** [comment]
@geetu040 how am I supposed to change the code? Thanks for help

**Comment by geetu040** [comment]
`query_text` param is not working for `qdrant_client.search` because you are using the wronge method here. Instead you should use `qdrant_client.query` that accepts `query_text` param

So, instead of this
```python
qdrant_client.search(collection_name="my_collection", query_text="my_text")
```

You code should look like this
```python
qdrant_client.query(collection_name="my_collection", query_text="my_text")
```

---

### Source Code Explanation

If you want to look into the source code then this explanation is for you
The class `QdrantClient` inherits the class `QdrantFastembedMixin`

[qdrant_client/qdrant_client.py](https://github.com/qdrant/qdrant-client/blob/master/qdrant_client/qdrant_client.py#L14)
```python
class QdrantClient(QdrantFastembedMixin):
	...
```

And the class `QdrantFastembedMixin` implements the `query` method you are looking for

[qdrant_client/qdrant_fastembed.py](https://github.com/qdrant/qdrant-client/blob/master/qdrant_client/qdrant_fastembed.py#L325)
```python
class QdrantFastembedMixin(QdrantBase):
    ...
    def query(
        self,
        collection_name: str,
        query_text: str,
        query_filter: Optional[models.Filter] = None,
        limit: int = 10,
        **kwargs: Any,
    ) -> List[QueryResponse]:
        ...
```

I hope this clears your concern, let me know if I am not being clear

**Comment by giacomobartoli** [comment]
Thanks a lot @geetu040. At this point I am afraid the readme is misleading.

**Comment by joein** [comment]
@giacomobartoli I briefly checked readme and could not find a mistake :(
Could you please point to the exact statement in readme which is incorrect?

**Comment by giacomobartoli** [comment]
My bad. Readme is correct. You can close this issue.
